<a href="https://colab.research.google.com/github/mohitv789/BookmarkAPI/blob/master/Fire_Crisis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving kaggle.json to kaggle.json

In [4]:
!mkdir kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle competitions download -c liberty-mutual-fire-peril

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)
Downloading train.csv.zip to /content
 99% 548M/554M [00:03<00:00, 181MB/s]
100% 554M/554M [00:03<00:00, 148MB/s]
Downloading test.csv.zip to /content
 96% 529M/553M [00:11<00:00, 50.5MB/s]
100% 553M/553M [00:12<00:00, 48.3MB/s]
Downloading sampleSubmission.csv.zip to /content
  0% 0.00/688k [00:00<?, ?B/s]
100% 688k/688k [00:00<00:00, 97.6MB/s]

In [7]:
!unzip test.csv.zip
!unzip train.csv.zip

Archive:  test.csv.zip
  inflating: test.csv
Archive:  train.csv.zip
  inflating: train.csv

In [1]:
import pandas as pd

# Import the test and train datasets into pandas dataframe
df_train = pd.read_csv('train.csv', header=0, sep=',', quotechar='"')
df_test = pd.read_csv('test.csv', header=0, sep=',', quotechar='"')

df_train.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   id  target var1  ... weatherVar234 weatherVar235 weatherVar236
0   1     0.0    Z  ...      2.355737      0.404655      0.138667
1   2     0.0    Z  ...      0.856632      0.231232      0.742199
2   3     0.0    3  ...      0.696013      0.693695      0.070654
3   4     0.0    3  ...      0.000000      0.000000      0.090332
4   5     0.0    Z  ...      1.338487      2.948202      0.816485

[5 rows x 302 columns]

In [2]:
for column in list(df_train):
  if df_train[str(column)].isnull().any():
    df_train[str(column)] = df_train[str(column)].fillna(df_train[str(column)].median())
  else:
    pass

In [17]:
for column in list(df_train):
  print(df_train[str(column)].isnull().any())

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False

In [19]:
df_train.dtypes

id                 int64
target           float64
var1              object
var2              object
var3              object
                  ...
weatherVar232    float64
weatherVar233    float64
weatherVar234    float64
weatherVar235    float64
weatherVar236    float64
Length: 302, dtype: object

In [29]:
import numpy as np
msk = df_train.dtypes == object

for i in range(len(msk)):
  if msk[i] == True:
    list_object.append()

False

In [10]:
list_object = []
list_number = []
df_number = pd.DataFrame()
df_object = pd.DataFrame()
for item in list(df_train):
  if df_train[item].dtype == object:
    list_object.append(item)
  else:
    list_number.append(item)
for col_num in list_number:
  df_number = pd.concat([df_number,df_train[col_num]],axis=1)
for col_obj in list_object:
  df_object = pd.concat([df_object,df_train[col_obj]],axis=1)

df_number.head()
df_object.head()

  var1 var2 var3 var4 var5 var6 var7 var8 var9 dummy
0    Z    Z    Z   N1    Z    Z    3    1    A     A
1    Z    Z    Z   C1    Z    Z    3    2    A     A
2    3    Z    4   J3    B    B    2    4    Z     B
3    3    Z    4   H1    B    Z    3    4    Z     B
4    Z    Z    Z   H1    Z    Z    2    4    A     A

In [13]:
df_var1 = pd.get_dummies(df_object.var1, prefix='var1')
df_var2 = pd.get_dummies(df_object.var2, prefix='var2')
df_var3 = pd.get_dummies(df_object.var3, prefix='var3')
df_var4 = pd.get_dummies(df_object.var4, prefix='var4')
df_var5 = pd.get_dummies(df_object.var5, prefix='var5')
df_var6 = pd.get_dummies(df_object.var6, prefix='var6')
df_var7 = pd.get_dummies(df_object.var7, prefix='var7')
df_var8 = pd.get_dummies(df_object.var8, prefix='var8')
df_dummy = pd.get_dummies(df_object.dummy, prefix='dummy')
df_number = pd.concat([df_number,df_var1,df_var2,df_var3,df_var4,df_var5,df_var6,df_var7,df_var8,df_dummy],axis=1)
df_number.head()

   id  target     var10        var11  ...  var8_6  var8_Z  dummy_A  dummy_B
0   1     0.0  3.898949   705.907218  ...       0       0        1        0
1   2     0.0  3.898949   778.939664  ...       0       0        1        0
2   3     0.0  4.314082   686.728476  ...       0       0        0        1
3   4     0.0  4.314082  3515.206111  ...       0       0        0        1
4   5     0.0  3.898949  1014.569367  ...       0       0        1        0

[5 rows x 389 columns]

In [23]:
y_train = df_number.target
X_train = df_number.drop(['target'], axis=1)
len(list(X_train))

388

In [21]:
for column in list(df_test):
  if df_test[str(column)].isnull().any():
    df_test[str(column)] = df_test[str(column)].fillna(df_test[str(column)].median())
  else:
    pass
# for column in list(df_test):
#   print(df_test[str(column)].isnull().any())

list_object2 = []
list_number2 = []
df_number2 = pd.DataFrame()
df_object2 = pd.DataFrame()
for item in list(df_test):
  if df_test[item].dtype == object:
    list_object2.append(item)
  else:
    list_number2.append(item)
for col_num in list_number2:
  df_number2 = pd.concat([df_number2,df_test[col_num]],axis=1)
for col_obj in list_object2:
  df_object2 = pd.concat([df_object2,df_test[col_obj]],axis=1)


df_var11 = pd.get_dummies(df_object2.var1, prefix='var1')
df_var12 = pd.get_dummies(df_object2.var2, prefix='var2')
df_var13 = pd.get_dummies(df_object2.var3, prefix='var3')
df_var14 = pd.get_dummies(df_object2.var4, prefix='var4')
df_var15 = pd.get_dummies(df_object2.var5, prefix='var5')
df_var16 = pd.get_dummies(df_object2.var6, prefix='var6')
df_var17 = pd.get_dummies(df_object2.var7, prefix='var7')
df_var18 = pd.get_dummies(df_object2.var8, prefix='var8')
df_dummy1 = pd.get_dummies(df_object2.dummy, prefix='dummy')
df_number2 = pd.concat([df_number2,df_var11,df_var12,df_var13,df_var14,df_var15,df_var16,df_var17,df_var18,df_dummy1],axis=1)
df_number2.head()

   id     var10        var11     var12  ...  var8_6  var8_Z  dummy_A  dummy_B
0  10  4.171214   774.596669  3.091641  ...       0       0        1        0
1  11  4.039930  3504.665319  3.091641  ...       0       0        1        0
2  14  3.776480   561.379551  3.091641  ...       0       0        1        0
3  16  4.314082  2352.045493  3.295300  ...       0       0        0        1
4  20  3.898949   504.975247  3.091641  ...       0       0        1        0

[5 rows x 388 columns]

In [ ]:
# from sklearn.preprocessing import PolynomialFeatures
# poly_reg = PolynomialFeatures(degree = 4)
# X_poly = poly_reg.fit_transform(X)
# lin_reg_2 = LinearRegression()
# lin_reg_2.fit(X_poly, y)

# # Visualising the Linear Regression results
# plt.scatter(X, y, color = 'red')
# plt.plot(X, lin_reg.predict(X), color = 'blue')
# plt.title('Truth or Bluff (Linear Regression)')
# plt.xlabel('Position Level')
# plt.ylabel('Salary')
# plt.show()

# # Visualising the Polynomial Regression results
# plt.scatter(X, y, color = 'red')
# plt.plot(X, lin_reg_2.predict(poly_reg.fit_transform(X)), color = 'blue')
# plt.title('Truth or Bluff (Polynomial Regression)')
# plt.xlabel('Position level')
# plt.ylabel('Salary')
# plt.show()

# # Visualising the Polynomial Regression results (for higher resolution and smoother curve)
# X_grid = np.arange(min(X), max(X), 0.1)
# X_grid = X_grid.reshape((len(X_grid), 1))
# plt.scatter(X, y, color = 'red')
# plt.plot(X_grid, lin_reg_2.predict(poly_reg.fit_transform(X_grid)), color = 'blue')
# plt.title('Truth or Bluff (Polynomial Regression)')
# plt.xlabel('Position level')
# plt.ylabel('Salary')
# plt.show()

# # Predicting a new result with Linear Regression
# lin_reg.predict([[6.5]])

# # Predicting a new result with Polynomial Regression
# lin_reg_2.predict(poly_reg.fit_transform([[6.5]]))